///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace jenkinsNew11
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the jenkinsNew11Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("b34a7048-cc1a-4d65-b518-99e710fed618")]
    public partial class jenkinsNew11Repository : RepoGenBaseFolder
    {
        static jenkinsNew11Repository instance = new jenkinsNew11Repository();

        /// <summary>
        /// Gets the singleton class instance representing the jenkinsNew11Repository element repository.
        /// </summary>
        [RepositoryFolder("b34a7048-cc1a-4d65-b518-99e710fed618")]
        public static jenkinsNew11Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public jenkinsNew11Repository() 
            : base("jenkinsNew11Repository", "/", null, 0, false, "b34a7048-cc1a-4d65-b518-99e710fed618", ".\\RepositoryImages\\jenkinsNew11Repositoryb34a7048.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b34a7048-cc1a-4d65-b518-99e710fed618")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class jenkinsNew11RepositoryFolders
    {
    }
#pragma warning restore 0436
}
